language: c
compiler:
 - gcc
env:
  global:
   - LUAROCKS_BASE=luarocks-2.2.2
   - HARFBUZZ_BASE=harfbuzz-1.0.1
   - GRAPHITE=true
   - ICU=true
  matrix:
   - LUA_VER=5.3 LUA_52_COMPAT=true LUA_53_BASE=lua-5.3.1
   - LUA_VER=5.3 LUA_52_COMPAT=false LUA_53_BASE=lua-5.3.1
   - LUA_VER=5.2
   - LUA_VER=5.2 GRAPHITE=false
   - LUA_VER=5.2 ICU=false
   - LUA_VER=5.1
before_install:
 - export LUA_PKG=lua$LUA_VER LUA_DEV=liblua$LUA_VER-dev LUA_SFX=$LUA_VER
   # Utility function for installing Noto fonts into the test environment
 - get_noto () {
     curl -Ls https://noto-website.storage.googleapis.com/pkgs/Noto$1-hinted.zip > $1.zip;
     unzip -d ~/.fonts -n $1.zip;
   }
   # Note installing graphite must be done before adding the SIL PPA because
   # their packages of the same name have broken dependencies
 - if $GRAPHITE; then sudo apt-get install -y libgraphite2-dev; fi
 - if $ICU; then
      sudo apt-get instal -y libicu-dev;
      curl -s -L https://gist.githubusercontent.com/alerque/1ad04c9502d8eafebffb/raw/8476ea675f6778f26635afbb946ec3cecd66d12a/icu_pkgconfig_files.tar | base64 -d | sudo tar xP;
   fi
   # Add SIL's PPA repository because it has newer versions of fonts
 - curl http://packages.sil.org/sil.gpg | sudo apt-key add -
 - echo 'deb http://packages.sil.org/ubuntu precise main' | sudo tee -a /etc/apt/sources.list
 - sudo apt-get update -qq
   # Sadly Lua 5.3 is not available from any PPA for Ubuntu 12.04 LTS (used by Travis)
 - if [ $LUA_VER = 5.3 ]; then
      sudo apt-get install libreadline-dev;
      wget http://www.lua.org/ftp/$LUA_53_BASE.tar.gz;
      tar xfz $LUA_53_BASE.tar.gz && pushd $LUA_53_BASE;
      $LUA_52_COMPAT || sed 's/-DLUA_COMPAT_5_2 //' -i src/Makefile;
      make linux && sudo make install && popd;
      wget -O lualib.tar.gz 'http://sourceforge.net/projects/luabinaries/files/5.3/Linux%20Libraries/lua-5.3_Linux313_64_lib.tar.gz/download';
      tar xfz lualib.tar.gz liblua53.so;
      sudo cp liblua53.so /usr/local/lib/;
      export LUA_INCDIR=/usr/local/include LUA_CONFIGURE_ARGS=(--lua-version=$LUA_VER --lua-suffix=$LUA_SFX --with-lua-include=$LUA_INCDIR);
   else
      sudo apt-get install -y $LUA_PKG $LUA_DEV;
      export LUA_INCDIR=/usr/include/lua$LUA_VER;
   fi
   # Install devel libraries and headers (for compiling libtexpdf)
 - sudo apt-get install -y lib{freetype6,fontconfig1,png,expat1}-dev
   # Install fonts (needed for typesetting regression tests)
 - sudo apt-get install -y fonts-sil-{scheherazade,lateef,gentium{,-basic}}
 - get_noto NaskhArabic && get_noto SansKannada && get_noto SansCJKJP
 - wget http://mirrors.kernel.org/ubuntu/pool/main/f/fonts-linuxlibertine/fonts-linuxlibertine_5.3.0-2_all.deb
 - sudo dpkg -i fonts-linuxlibertine_5.3.0-2_all.deb
   # Install luarocks (to later fetch SILE runtime dependencies)
 - wget http://luarocks.org/releases/$LUAROCKS_BASE.tar.gz
 - tar xfz $LUAROCKS_BASE.tar.gz && pushd $LUAROCKS_BASE
 - ./configure $LUA_CONFIGURE_ARGS && sudo make && sudo make install && popd
 - wget http://www.freedesktop.org/software/harfbuzz/release/$HARFBUZZ_BASE.tar.bz2
 - tar xfj $HARFBUZZ_BASE.tar.bz2 && pushd $HARFBUZZ_BASE
 - ./configure --with-graphite2=auto && make && sudo make install && popd
 - sudo ldconfig
   # Install SILE runtime dependencies
 - sudo luarocks install lpeg
 - sudo luarocks install luaexpat
 - sudo luarocks install luafilesystem
 - sudo luarocks install lua_cliargs 2.3-3
 - sudo luarocks install busted
script:
 - ./bootstrap.sh && ./configure && make
 - busted -m './lua-libraries/?.lua;./lua-libraries/?/init.lua' tests
 - ./tests/attack.pl
 - ./tests/attack.pl --regression
