name: Luacheck

on: [push, pull_request]

jobs:

  luacheck:
    runs-on: ubuntu-20.04
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Setup ‘lua’
      uses: leafo/gh-actions-lua@v8
      with:
        luaVersion: 5.3
    - name: Setup ‘luarocks’
      uses: leafo/gh-actions-luarocks@v4
    - name: Setup ‘luacheck’
      run: |
        luarocks install luacheck
        luarocks install lanes
    - name: Run ‘luacheck’ linter
      run: luacheck -j$(nproc) .
